### ISSUE TITLE
Manual testing checklist. Summaries with custom tags

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#1013]
**Initial set-up**

*Check that the IntelliJ Idea UTBot plugin can be successfully installed*

- [x] [Choose appropriate workflow from the list](https://github.com/UnitTestBot/UTBotJava/actions/runs/3127050936)
- [x] Download plugin
- [x] Check downloaded zip-file size < 100 MB
- [x] Open IntelliJ IDEA 2022.1.4
- [x] Remove previously installed UTBot plugin
- [x] Clone or reuse UTBot project (https://github.com/UnitTestBot/UTBotJava.git)
- [x] Open the project in the IDE
- [x] Install the downloaded plugin

*Go through manual scenarios*

**Manual scenario #1**

- [x] Use default plugin setting / or turn Fuzzing off
- [x] Check: File -> Settings -> Tools -> UnitTestBot -> Javadoc comment style is "Structured via custom Javadoc tags"
- [x] Open the utbot-sample/src/main/java/org/utbot/examples/algorithms/ArraysQuickSort.java file
- [x] Generate tests for the class
blocked by #1001 
- [ ] Check Java docs, all tags are correct
- [ ] Render Java doc
reproducing #985 
 
**Manual scenario #2**

- [x] Use default plugin settings. 
- [x] Check: File -> Settings -> Tools -> UnitTestBot -> Javadoc comment style is "Structured via custom Javadoc tags"
- [x] Open the utbot-sample/src/main/java/org/utbot/examples/mock/CommonMocksExample.java file
- [x] Generate tests with different Mocking options combinations
- [ ] Check Java docs, all tags are correct
- [ ] Render Java doc
reproducing #985 
 
**Manual scenario #3**

- [x] Use default plugin settings. 
- [x] Check: File -> Settings -> Tools -> UnitTestBot -> Javadoc comment style is "Structured via custom Javadoc tags"
- [x] Open the utbot-sample/src/main/java/org/utbot/examples/recursion/Recursion.java file
- [x] Generate tests for the methods
- [x] Check Java docs, all tags are correct
- [x] Render Java doc
new bug: @utbot.triggersRecursion tag is missing
 
**Manual scenario #4**

- [x] Use default plugin settings. 
- [x] Check: File -> Settings -> Tools -> UnitTestBot -> Javadoc comment style is "Structured via custom Javadoc tags"
- [x] Open the utbot-sample/src/main/java/org/utbot/examples/exceptions/ExceptionExamples.java
- [x] Generate tests for the methods
- [x] Check Java docs, all tags are correct, @utbot.caughtException should be present
- [x] Render Java doc
- [x] File -> Settings -> Tools -> UnitTestBot -> Javadoc comment style set to "Plain text"
- [x] Generate tests for the class
- [ ] Check Java docs, all tags are correct
- [ ] Render Java doc
reproducing #985 

**Manual scenario #5**

- [ ] Create a new Maven project with JDK 8
- [ ] Use default plugin settings. 
- [ ] Check: File -> Settings -> Tools -> UnitTestBot -> Javadoc comment style is "Structured via custom Javadoc tags"
- [ ] Add a simple java file to test
- [ ] Generate a test with a new test root
- [ ] Check Java docs, all tags are correct
- [ ] Render Java doc

**Manual scenario #6**

- [ ] Create a new Idea project with JDK 11
- [ ] Use default plugin settings. 
- [ ] Check: File -> Settings -> Tools -> UnitTestBot -> Javadoc comment style is "Structured via custom Javadoc tags"
- [ ] Add a simple java file to test
- [ ] Generate tests for several classes
- [ ] Check Java docs, all tags are correct
- [ ] Render Java doc
