### ISSUE TITLE
Testing of UI checklist 2.1 RC#165

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#1055]
### UI plugin checklist
**Install plugin**
Build under test - https://github.com/UnitTestBot/UTBotJava/actions/runs/3172776185
- [x] Open IntelliJ IDE
- [x] Uninstall previously installed UTBot plugin (if present)
- [x] Install the downloaded plugin
- [x] Clone or reuse UTBot project (https://github.com/UnitTestBot/UTBotJava.git)
- [x] Open the project in the IDE

**Make the following checks for IntelliJ, Maven, Gradle projects with different JDK 8/11**

**Open dialog**

- [x] Open the `utbot-sample/src/main/java/org/utbot/examples/algorithms/ArraysQuickSort.java` file
- [x] From code. Open context menu, select Generate..., select Create tests with UTBot... => Dialog is opened
- [x] Context menu item is disabled for non Java classes, for example resources, configuration files

**Dialog. Members**

- [x] From _Project view_. Right-click on a **package with several classes**, select Create tests with UTBot... => Dialog is opened. All classes from package are listed and selected 
- [x] From _Project view_. **Select several classes**, right-click, select Create tests with UTBot... => Dialog is opened. Selected classes are listed and selected
- [x] From _Project view_. Right-click on **one class**, select Create tests with UTBot... => Dialog is opened. All methods of the class are listed and selected (except private)
- [x] Create a public class with 4 different methods: private, without access modifier, protected, public. Open UTBot test generation for the class => all methods except private are in list. - check for Kotlin/Java
- [x] Make the class **package-private** (remove "public") => check the same

**Dialog. Settings**

*Verify tests are generated with all these options*

- [x] Dialog. Test source root is defaulted (if test source root is set in project)
reproducing #786 
- [x] Dialog. Test source root (if no test sources root set in project) => suggests to create a new one (red) - create => verify created
- [x] check in Gradle #1060 
- [x] check in IntelliJ
- [x] check in Maven (@alisevych )
- [x] Dialog. Test framework => is defaulted to JUnit5
- [x] Dialog. Test framework (for project with JDK 8) => JUnit4, JUnit5 only
- [x] Dialog. Test framework (for project with JDK 11) => JUnit4, JUnit5, TestNG (not existing in project dependencies must have red text "(will be installed)")
- [x] check in Gradle
- [x] check in IntelliJ
- [x] check in Maven (@alisevych)
- [x] Dialog. Mock strategy => 1) `Do not mock`, 2) `Mock package environment`, 3) `Mock class environment`
- [x] Dialog. Mock strategy "Do not mock" is selected => `Mock static methods` is unchecked and disabled
- [x] Dialog. Mock strategy - select 2) and 3) options => Mock static options: 1) 'Mock static methods' checked, 2) 'Mock static methods' unchecked.
- [x] Dialog. Mock strategy (for a project without Mockito in dependencies) => 2), 3) options have red text "(will be installed)"
- [x] check in Maven (@alisevych)
- [x] Dialog. Timeout for class => default to 60 sec, only natural numbers can be saved, up and down arrows work
to correct field #977
- [x] Dialog. Timeout for class => minimize, check on ArrayQuickSort or some other code with conditions and loops
bug #1028 
- [x] Dialog. Parametrized test => 2 options: Not parametrized / Parametrized 
- [x] Dialog. Parametrized test - select "Parametrized" => "No mocks" and "No static mocking" are chosen and both disabled
- [x] Dialog. Destination package. Check not present // change request:
#488 

**SARIF report**

- [x] Dialog. Uncheck "Parametrized tests" , generate tests => SARIF report is generated into resources folder - in correct package
- [x] do this for a single class => check place, package, file
- [x] do this for several classes in different packages 
- [ ] Dialog. Check "Parametrized tests", generate tests => no SARIF report is generated
#980 

**File -> Settings... -> UTBot**
- [x] Force static mocking. Add a class... 
- [x] Code analysis. Select Simplest, Deepest, 1st mark from left, 1st mark from right, somewhere in the middle...
#1064

**Comment by alisevych** [comment]
new bug #1059  - Maven / IntelliJ projects - Test sources root folder
