### ISSUE TITLE
Checklist for Kotlin support smoke testing

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotJava#1268]
**UTBot settings**
- [ ] Handling test timeout
- [x] Test with exceptions
  - [x] Pass
  - [x] Fail
- [x] Overflow detection - #1272
  - [x] Ignore overflows
  - [x] Treat overflows as errors
- [x] Javadoc comment style: not properly structured - #842 ? or create dedicated issue
  - [x] Structured
  - [x] Plain
- [x] Display detected errors on the Problems tool window
- [x] Enable Summaries Generation
- [x] Force mocking static methods - #1278
- [x] Test generation method

**Test generation settings**
- [x] Test sources root
- [x] Testing framework
  - [x] TestNG
  - [x] JUnit 4
  - [x] JUnit 5
- [ ] Mocking strategy
  - [x] Do not mock
  - [x] Mock everything outside the package - #1278
  - [ ] Mock everything outside the class - #1278
- [ ] Mock static methods
- [x] Parameterized tests - #1104
- #1221
- [x] Test generation timeout
- [x] Generate tests for

**Environments**
- [x] Intellij IDEA 
  - [x] 2022.2.3 @tyuldashev 
  - [x] 2022.1.4 @alisevych 
- [x] JDK
  - [x] 11 @tyuldashev 
  - [x] 17 @alisevych 
- [x] Kotlin
  - [x] 1.7.20
