### ISSUE TITLE
Rider plugin release chores

### ISSUE THREAD

**Issue by Domonion** [UnitTestBot/UTBotJava#1488]
**Description**

Before releasing plugin on Jetbrains Plugin marketplace several things should be done in advace:

- [x] Rider alpha version - #1120 moved to #1463 and #1484
- [x] Rider plugin build workflow - #1462 and #1463
- [x] plugin xml, change notes, gifs, landing page - #1487
- [x] utbot.org` C# playground and demos - @victoriafomina 

This is parent issue for everything related to UtBot C# plugin

**Comment by Domonion** [comment]
Closed as released in [2022.12](https://github.com/UnitTestBot/UTBotJava/releases/tag/2022.12)
