### ISSUE TITLE
Manual testing of Release 2023.03 Part 3

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#1864]
**Initial set-up**

Add link to Plugin build #***

- [x] Sarif report + Problems view
- [x] Cancellation of generation (with Generate / Generate & Run)
- [x] Java docs styles
- [x] Sandboxing
- [ ] Logging
- [x] Hanging test timeout, check with Fuzzing/Symbolic
- [x] Overflows, check Summaries
- [x] Context estimator, check nightly runs
- [ ] Bugs list

**Comment by alisevych** [comment]
### Security testing (sandboxing)

**Basic security**

- [ ] Project with JDK 8 + manual scenario from PR #625 + default settings
- [ ] Fuzzing only
- [ ] Symbolic execution only
- [ ] Project with JDK 11 + default settings
- [ ] Fuzzing only
- [ ] Symbolic execution only
- [ ] Concrete executor is invoked from Symbolic execution
- [ ] Project with JDK 17 + default settings

**With permissions**

- [ ] add PropertyPermission in ~\.utbot\sandbox.policy - check test for property is not in sandbox, execute
- [ ] add "permission java.io.FilePermission  "<<ALL FILES>>", "read";" - check test for read not in sandbox, execute
- [ ] add AllPermission  in ~\.utbot\sandbox.policy - check NO tests are in sandbox, try to execute (carefully!!!)
- [ ] corrupt permission - check how UTBot fails  - try scenario from #796
- [ ] empty file
- [ ] remove ~\.utbot\sandbox.policy file - check generated tests are in sandbox

**Test rendering**

- [ ] JUnit4
- [ ] JUnit5
- [ ] TestNG
- [ ] JUnit5 with parametrization
- [ ] TestNG with parametrization

**Code structures**

- [ ] in private method
- [ ] bug to check: #791

**Comment by alisevych** [comment]
Reproducing:
- #1314
