### ISSUE TITLE
Spring support manual testing checklist

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#2265]
**Initial set-up**

*Check that the IntelliJ Idea UTBot plugin can be successfully installed*

- [x] Choose appropriate workflow from the list (by default, filter by main branch and take the latest one) https://github.com/UnitTestBot/UTBotJava/actions/workflows/publish-plugin-and-cli.yml
- [x] Download plugin
- [x] Check downloaded zip-file size < 100 MB
- #2159 
- [x] Open IntelliJ IDEA Ultimate 2023.1
- [ ] Check Spring plugins are bundled
- [x] Remove previously installed UTBot plugin
- [x] Install the downloaded plugin

*Checks for spring-petclinic project*

- [x] Gradle project with JDK 17
- [ ] Maven project with JDK 11
- [ ] IntelliJ project with JDK 1.8

*Check No Configuration mode + Unit tests*

- [ ] `@Entity` + No Configuration + Unit tests + Generate tests
- [ ] `PetTypeFormatter` + No Configuration + Unit tests + Generate and Run
- [ ] `@Controller` + No Configuration + Unit tests
- [ ] Java class without annotation + No Configuration + Unit tests

*Check Spring configuration + Unit tests*

- [x] `@Entity` + `@SpringBootApplication` + Unit tests + Generate tests
- [ ] `@Controller` + `@SpringBootApplication` + Unit tests + Generate and Run

*Check Unit tests + test runners*

- [ ] `@SpringBootApplication` + Unit tests + JUnit4 + Generate and Run
- [ ] XML configuration + Unit tests + JUnit5 + Generate and Run
- [ ] Java class `@Configuration` + Unit tests + TestNG + Generate and Run
- [ ] Java class `@TestConfiguration` + Unit tests + JUnit5 + Generate and Run

*Check  No Configuration mode + Mocking strategy
Copy-paste sample classes into Spring project*

- [ ] No Configuration + Unit tests + No mocks
- [ ] No Configuration + Unit tests + Mock everything outside class
- [ ] No Configuration + Unit tests + Mock everything outside package

*Check Spring configuration + Integration tests*

- [ ] `@SpringBootApplication` + Integration tests + JUnit5 + Generate and Run
- [ ] XML configuration + Integration tests + JUnit4
- [ ] Java class `@Configuration` + Integration tests + JUnit4
- [ ] Java class `@TestConfiguration` + Integration tests + TestNG

**Comment by alisevych** [comment]
Found bugs:
- #2291 
- #2292
