### ISSUE TITLE
Testing of Java 11 features checklist

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#407]
**Initial set-up**

*Check that the IntelliJ Idea UTBot plugin can be successfully installed*

- [x] Plugin [downloaded from here](https://github.com/UnitTestBot/UTBotJava/actions/runs/2612161368) and installed in IntelliJ IDEA 2022.1.3

**Create code samples for Java features and generate tests for them:**

- [x] String methods: isBlank(), lines(), repeat(), strip(), stripLeading(), stripTrailing() 
**Are supported when fixing #375** 
- [x] Reflection API: new methods: getNestHost(), getNestMembers(), and isNestmatOf()
- [x] File static methods: readString() and writeString()
- [x] Collection to an Array
  - #525
- [x] not() method in Predicate
 - related - #448 
- [x]  HTTP Client API
  - #909
- [x]  Local-Variable syntax for lambda expressions  - allow usage of  annotations like @NotNull or @Nullable with the parameters. 
  waiting merge of lambda support - #825
