### ISSUE TITLE
UI checklist 1.0

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#475]
### UI plugin checklist - version 1.0

**Install plugin**

- [x] Choose appropriate workflow from the next list (by default, use the latest one) https://github.com/UnitTestBot/UTBotJava/actions/workflows/publish-plugin-and-cli.yml
- [x] Open IntelliJ IDE
- [x] Uninstall previously installed UTBot plugin (if present)
- [x] Install the downloaded plugin
- [x] Clone or reuse UTBot project (https://github.com/UnitTestBot/UTBotJava.git)
- [x] Open the project in the IDE

**Make the following checks for IntelliJ, Maven, Gradle projects with different JDK 8/11**

**Open dialog**

- [x] Open the utbot-sample/src/main/java/org/utbot/examples/algorithms/ArraysQuickSort.java file
- [x] From Project view. Right-click on one **class**, select Create tests with UTBot... => Dialog is opened. All methods from class are listed and selected
- [x] From code. Open context menu, select Generate..., select Create tests with UTBot... => Dialog is opened
- [x] Shortcut. Cursor on the **class** and outside all methods, press Alt+Shift+U => all class methods are selected
- [x] Shortcut. Cursor on/inside **one method**, press Alt+Shift+U => correct method is selected
- [x] Shortcut. Not working from build.gradle file, Java class file in test sources root, resources, etc.
- [x] Context menu item is disabled for --||--

**Dialog. Members**

- [x] From Project view. Right-click on a **package with several classes**, select Create tests with UTBot... => Dialog is opened. All classes from package are listed and selected 
- [x] From Project view. **Select several classes**, right-click, select Create tests with UTBot... => Dialog is opened. Selected classes are listed and selected
- [x] From Project view. Right-click on **one class**, select Create tests with UTBot... => Dialog is opened. All methods of the class are listed and selected (except private)
- [x] Create a public class with 4 different methods: private, without access modifier, protected, public. Open UTBot test generation for the class => all methods except private are in list.
- [x] Make the class **package-private** (remove "public") => check the same

**Dialog**

*Verify tests are generated with all these options*

- [x] Dialog. Test source root is defaulted (if test source root is set in project)
- [x] Dialog. Test source root (if no test sources root set in project) => suggests to create a new one (red) - create => verify created
- [x] Dialog. Code generation language. Default is Java // change request:
#500
- [x] Dialog. Code generation language => Java, Kotlin
- [x] Dialog. Test framework => is defaulted to JUnit5 // change request:
#499
- [x] Dialog. Test framework (for project with JDK 8) => JUnit4, JUnit5 only // change request:
#309 
- [x] Dialog. Test framework (for project with JDK 11) => JUnit4, JUnit5, TestNG (not existing in project dependencies must have red text "(will be installed)")
- [x] Dialog. Mock strategy => 1) No mocks, 2) Other packages: Mockito, 3) Other classes: Mockito
- [x] Dialog. Mock strategy "No mocks" is selected => Mock static is set to "No static mocking" and disabled
- [x] Dialog. Mock strategy - select 2) and 3) options => Mock static options: 1) No static mocking, 2) Mockito static mocking.
- [x] Dialog. Mock strategy (for a project without Mockito in dependencies) => 2), 3) options have red text "(will be installed)"
- [x] Dialog. Timeout for class => default to 60 sec, only natural numbers can be saved, up and down arrows work
- [x] Dialog. Parametrized test => 2 options: Not parametrized / Parametrized 
- [x] Dialog. Parametrized test - select "Parametrized" => "No mocks" and "No static mocking" are chosen and both disabled
- [x] Dialog. Destination package. Check not present // change request:
#488

**Comment by alisevych** [comment]
@amandelpie I'm pretty sure that it is possible. This is the base for the future automation.
There are several possible UI TA tools. Investigation is needed to verify which of them suits fine for the project. That depends not only on how they interact with IDEA UI. But also on how these tests are integrated into CI/CD process.
That's a pleasant thing to do but that's not the first priority for now. There are core functional cases to analyze manually and cover them first.
