### ISSUE TITLE
Test checklist for Security Manager

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#790]
**Initial set-up**

*Check that the IntelliJ Idea UTBot plugin can be successfully installed*

- [x] Choose appropriate workflow from the list - with Security Manager included - [plugin build used](https://github.com/UnitTestBot/UTBotJava/actions/runs/2919016682)
- [x] Download plugin
- [x] Open IntelliJ IDE
- [x] Remove previously installed UTBot plugin
- [x] Install the downloaded plugin

*Go through manual scenarios*

**Basic security**

- [x] Project with JDK 8 + manual scenario from PR #625 + default settings
- [x] Fuzzing only
- [x] Symbolic execution only
- [x] Project with JDK 11 + default settings, bug found: #792
- [x] Fuzzing only
- [x] Symbolic execution only
- [ ] ??? Concrete executor is invoked from Symbolic execution ???

Project with JDK 17 - blocked as UTBot is incompatible with JDK 12+

**Permissions**

- [x] add PropertyPermission in ~\.utbot\sandbox.policy - check test for property is not in sandbox, execute
- [x] add "permission java.io.FilePermission  "<<ALL FILES>>", "read";" - check test for read not in sandbox, execute
- [x] add AllPermission  in ~\.utbot\sandbox.policy - check NO tests are in sandbox, try to execute (carefully!!!)
- [x] corrupt permission - check how UTBot fails -  found #796
- [x] empty file
- [x] remove ~\.utbot\sandbox.policy file - check generated tests are in sandbox

**Test rendering**

- [x] JUnit4
- [x] JUnit5
- [x] TestNG
- [x] JUnit5 with parametrization - #620 reproducing
- [x] TestNG with parametrization

**Code structures**

- [x] in private method
- [x] in static block of a used class - bug found: #791
- [x] in compiler of a used class - bug found: #791 
- [x] in a separate thread - not yet supported - enhancement: #895
