### ISSUE TITLE
Kotlin features support testing checklist

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#955]
**Initial set-up**

- [x] [Download latest plugin build from main ](https://github.com/UnitTestBot/UTBotJava/actions/runs/3080551289)
- [x] Open IntelliJ IDEA 2022.1.4
- [x] Remove previously installed UTBot plugin
- [x] Install the downloaded plugin

**Smoke manual test**

- [x] New Gradle project with Kotlin language, JDK 11
- [x] Kotlin class with simple function
- [x] Generate tests with UTBot with default settings
- [x] Check generated tests

**IDE related support**

- [ ] IDEA 2022.1.4 (JRE 11) + `kotlin 1.7.10`
- [x] IDEA 2022.2.3 (JRE 17) + `kotlin 1.7.20`
- [ ] Android Studio Chipmunk + `kotlin 1.7.10`

**Generation settings**

- [x] Symbolic 95%
- [ ] Fuzzing 100%
- [ ] Symbolic 100%

**Kotlin features to test**

*Top developer functions*

- [ ] primary constructors
- [ ] sequences
- [x] Instance checks﻿ (when statements) - `SealedClasses`, `SmartCasts`

*[Kotlin Idioms](https://kotlinlang.org/docs/idioms.html)*

- [ ] Create DTOs - `DataClassExample`, `AssociationAndGrouping`
- [x] Default values for function parameters﻿ - `DefaultArguments.kt`
- [ ] Filter a list﻿ - `ListSample`
- [ ] String interpolation
- [ ] Read-only list﻿ - `ListSample.findLastGreaterThanN()`
- [ ] Read-only map - `MapSample.updatePointsCredit()`
- [ ] Access a map entry - `MapSample.mapElementAccess()`
- [ ] map.foreach() better  - `MapSample.accountsReport`
- [ ] Iterate over a range﻿ 
- [ ] Lazy property﻿
- [ ] Extension functions﻿ - `ExtensionFunctions.kt`
- [ ] Create a singleton
- [ ] Instantiate an abstract class - anonym classes
- [ ] If-not-null-else shorthand
- [ ] Execute a statement if not null - with throw or return
- [ ] Get first item of a possibly empty collection﻿ - `MapSample.getOrElseCase()`
- [ ] Scope functions: let, apply, ...
- [x] Return on when statement﻿ - `SealedClasses`, `SmartCasts`
- [ ] try-catch expression
- [ ] if expression﻿
- [ ] Builder-style usage of methods that return Unit 
- [ ] Call multiple methods on an object instance (with)﻿
- [ ] Configure properties of an object (apply)﻿
- [ ] Java 7's try-with-resources﻿
- [ ] Mark code as incomplete (TODO)﻿

*Extra cases*

- [ ] Test UTBot on UTBot utbot-intellij/.../org/utbot/intellij/plugin/ui/actions/GenerateTestsAction.kt
bug #965
- [ ] rename on import - `RenameOnImport.kt`
- [ ] check object in range with compareTo - `Comparison.kt`
- [ ] Create Error example with invalid compareTo - that leads to interrupting range of objects of the class

*Functions*

- [x] simple functions - `SimpleFunctions`
- [x] infix functions - `InfixFunctions`
- [x] inner class
- [ ] overload operators - `Operators`
- [ ] top level functions - `TopLevel.kt`
- [ ] vararg arguments - `VarArgs`

**Comment by alisevych** [comment]
New bugs found by @tyuldashev 
- #1255 
- #1256 
- #1257 
- #1258 
- #1259 
- #1260 
- #1262

**Comment by alisevych** [comment]
Other settings checklist:
- #1268

**Comment by alisevych** [comment]
added bugs:
- #1271 
- #1273

**Comment by denis-fokin** [comment]
Currently, not topmost priority.
